<?php

return [
	'page' => ' - page {0}',
	'start' => 'Start',
	'first' => 'First',
	'last' => 'Last',
	'greet' => 'Hello there {0} one!',
	'error_msg' => 'There was some errors:',
	'error_bad_token' => 'User verification failed miserably, it was probably your fault!',
	'error_possible_bot' => 'You had harvested enough data for today boy, go get some rest',
	'error_empty_email' => 'Empty email field. Seriously, how could you forgot to type it?',
	'error_empty_password' => 'Empty password field. Nope, your password isn\'t 1234.',
	'error_bad_email' => 'The email you provided isn\'t valid, Dunno why.',
	'error_no_user' => 'I am legally forced to tell you there are no records of an user ever registered here with the credentials you provided. <strong>Protip:</strong> Go back in time and register an account then come back and try again.',
	'signup' => 'Not an user? mmm how about <a href="{0}">signing up?</a>',
	'signin' => 'Sign in',
	'logout' => 'logout',
	'login' => 'login something',
	'login_success' => 'Welcome aboard pal!',
	'logout_success' => 'phew... are you glad is it over? yeah.. me too!',
	'login_password' => 'Password',
	'login_email' => 'Email',
	'submit' => 'Submit',
];
